// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": Application User Types
//
// Command:
// $ goagen
// --design=github.com/akm/goa_gae_datastore_example/design
// --out=$(GOPATH)/src/github.com/akm/goa_gae_datastore_example
// --version=v1.3.1

package client
